apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-one-pipe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-one-pipe
  template:
    metadata:
      labels:
        app: the-one-pipe
    spec:
      containers:
        - name: the-one-pipe
          image: henriquess/the-one-pipe:3.0.4
          ports:
            - containerPort: 8080 