apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipe-services-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-ipstream: "true"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /dotnet
        pathType: ImplementationSpecific
        backend:
          service:
            name: dotnet-pipe-service
            port:
              number: 80
      - path: /java
        pathType: ImplementationSpecific
        backend:
          service:
            name: the-one-pipe-service
            port:
              number: 80
        