apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipe-services-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /dotnet
        pathType: Prefix
        backend:
          service:
            name: dotnet-pipe-service
            port:
              number: 8087
      - path: /java
        pathType: Prefix
        backend:
          service:
            name: the-one-pipe-service
            port:
              number: 8088