apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipe-services-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-ipstream: "true"
spec:
  rules:
  - host: demopipe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            serviceName: hello-world-service
            servicePort: 8080
      - path: /dotnet
        pathType: Prefix
        backend:
          service:
            serviceName: dotnet-pipe-service
            servicePort: 8080
      - path: /java
        pathType: Prefix
        backend:
          serviceName: the-one-pipe-service
          servicePort: 8080
        