apiVersion: v1
kind: Service
metadata:
  name: dotnet-pipe-service
  namespace: demo-ingress
spec:
  selector:
    app: dotnet-pipe
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 5000
  type: NodePort

