apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: demo-ingress
spec:
  selector:
    app: hello-world 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
