apiVersion: v1
kind: Service
metadata:
  name: the-one-pipe-service
spec:
  selector:
    app: the-one-pipe  
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32522
  type: NodePort
