apiVersion: v1
kind: Service
metadata:
  name: the-one-pipe-service
spec:
  selector:
    app: the-one-pipe  
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30000
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 5000
      nodePort: 30001
  type: NodePort
