apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: java-app-bluegreen
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: henriquess/java-app:0.30.0 # Blue version initially
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: java-app-active
      previewService: java-app-preview
      autoPromotionEnabled: false  # Manual promotion after validation
